version: '3'
services:

  polkadot:
    image: parity/polkadot:v0.8.24
    volumes:
      - "polkadot-data:/data"
    command: --rpc-external --prometheus-external --log error --rpc-cors=all --ws-external --chain=local

  vedran:
    command: start --auth-secret=test-secret --log-level debug --public-ip vedran --server-port 4000
    image: nodefactory/vedran:v0.2.0
    ports:
      - "4000:4000"
    container_name: "vedran"

  vedran-daemon:
    image: nodefactory/vedran-daemon:v0.2.0
    depends_on:
      - vedran
      - polkadot
    command: --id test-id --lb http://vedran:4000 --node-rpc http://polkadot:9615 --node-metrics http://polkadot:9615 --payout-address 0xtestaddress --log-level info

volumes:
  polkadot-data:
